name: Check Memoise Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: "18"
 
      - name: Install dependencies
        run: npm ci


      - name: Ejecutar esLint
        run: npm run eslint


      - name: Test
        run: npm test